BBS14/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app01/',include('app01.urls')),
    path('testapp/',include('testapp.urls')),
    # path('search/',include('haystack.urls'))
]

from BBS14 import settings
from django.conf.urls.static import static
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app01/urls.py
from django.urls import path, re_path
from . import views

# from app01 import search_views

urlpatterns = [
    # 注册
    path('register/', views.register, name='app01_register'),
    # 登录
    path('login/', views.login, name='app01_login'),
    # 主页面
    path('home/', views.home, name='app01_home'),
    # 显示文件资源的页面
    path('file_home/', views.file_home, name='app01_file_home'),
    # 获取验证码图片
    path('get_code/', views.get_code, name='app01_get_code'),
    # 退出登录
    path('logout/', views.logout, name='app01_logout'),
    # 修改密码
    path('set_password/', views.set_password, name='app01_set_pwd'),
    # 个人站点
    path('site/<str:username>/', views.site, name='app01_site'),
    # 侧边栏筛选功能，多个url指向site的·视图函数，
    path('site/<str:username>/tag/<int:tag_id>/', views.site),
    path('site/<str:username>/category/<int:category_id>/', views.site),
    path('site/<str:username>/archive/<str:archive_month>/', views.site),
    #资源库的分类
    path('site/<str:username>/categorys/<int:web_source_id>/', views.site),
    # 两个视图数是一样的，那么视图函数接收的函数就是不确定了，要使用**kwargs或*args来接收
    # re_path('stite/(?P<username>\w+)/(?P<condition>tag|category|archive)/(?P<param>.*)/',views.site)
    # 文章详情页
    path('site/<str:username>/article/<int:article_id>/', views.article_detail, name='app01_article'),
    # 点赞或点踩功能
    path('up_or_down/', views.up_or_down, name='app01_up_or_down'),
    # 文章评论的url
    path('article/comment/', views.comment, name='app01_comment'),
    # 后台管理
    path('backend/', views.backend, name='app01_backend'),
    # 添加文章
    path('backend/add_article/', views.add_article, name='app01_add_article'),
    # 编辑器上传图片的接收路径
    path('upload/img/', views.upload_img, name="app01_uploadImg"),
    # 修改用户头像
    path('change_avatar/', views.chang_avatar, name='app01_change_avatar'),
    # 个人资料修改：
    path('change_datas/', views.change_datas, name='app01_change_datas'),
    #展示我的班级的所有人
    path('myclass/',views.MyClass,name='app01_myclass'),
    # 修改文章
    path('editor_article/', views.editor_article, name='app01_editor_article'),
    # 文件上传
    path('upload_file/', views.upload_file, name='app01_upload_file'),
    # 操作文章
    path('operate_file/', views.operate_file, name='app01_operate_file'),
    # 文件下载
    path('download/file/', views.download_file, name='app01_download_file'),
    # 文件预览
    path('preview_file/', views.preview_file, name='app01_preview'),
    # 文章的收藏
    path('cellct_article/', views.cellact_article, name='app01_cellact_article'),
    # 文件收藏展示
    path('file_cellation/', views.file_cellation, name='app01_fi_cellation'),
    # 文章收藏展示
    path('article_cellation', views.article_cellation, name='app01_ar_cellation'),
    # 找回密码的路由
    path('find_password/', views.find_password, name='app01_find_password'),
    # 搜索的
    path('search/', views.search, name='app01_search'),
    # 个人站点上的文件显示
    path('site/<str:username>/file/', views.site_file, name="app01_site_file"),
    # 关注的视图函数
    path('focu/user/', views.focu_user, name="app01_focu_user"),
    # 我的关注
    path('my_focu/', views.my_focu, name='app01_my_focu'),
    # 管理员的账户
    path('admin/', views.admin_home, name='app01_admin_home'),
    path('admin/teacher/', views.admin_teacher, name='app01_admin_teacher'),
    path('admin/article/', views.admin_article, name='app01_admin_article'),
    path('admin/files/', views.admin_file, name='app01_admin_file'),
    #上传可以管理员批量导入用户的文件
    path('admin/upload/',views.admin_upload,name = 'app01_admin_upload'),
    #展示管理员文件，并可以批量导入
    path('admin/upload/files/', views.admin_upload_files, name='app01_admin_upload_files'),
    #批量导入用户的
    path('admin/add/users/',views.admin_add_users,name='app01_admin_add_users'),
    path('admin/delete/',views.delete),
    #修改管理员信息
    path('change_admin/',views.change_admin,name='app01_change_admin'),
    #增加管理员账户
    path('add_admin/',views.add_admin,name='app01_add_admin'),
    #显示所有的管理员
    path('show_admin/',views.show_admin,name='app01_show_admin'),
    #临时设置班级的
    path('set/',views.set),
    #增加单个用户
    path('admin_add_user/',views.admin_add_user,name='app01_admin_add_user'),
    #老师管理学生
    path('manage_student/',views.manage_student,name="app01_manage_stu"),
    #私信的url
    path('userwechat/',views.userWechat,name='app01_wechat'),
    #未读消息
    path('message/',views.message,name='app01_message'),
    path('admin_user_comment/',views.admin_user_comment),
    #web资源分类
    path('web_sourse/',views.web_sourse,name='app01_web_sourse'),
    #上传web资源
    path('up_web_source/',views.up_web_source,name='app01_up_web_source'),
    #展示资源的url,下载原代码
    path('show_web_source/',views.show_web_source,name='app01_show_web'),
    #展示所有资源的页面
    path('web_home/',views.web_home,name='app01_web_home'),
    #资源详细展示出来
    path('site/<str:username>/source_detail/<int:sou_pk>/',views.source_detail,name='app01_source_detail'),
    #资源收藏
    path('source/collection/',views.source_collection,name='app01_sou_colle'),
    #管理用户的资源
    path('admin/source/',views.admin_source,name='app01_admin_source'),
    path('editer/source/',views.editer_source,name='app01_editer_source'),



]

app01/models.py
from django.db import models

# Create your models here.
'''
先写普通字段
之后再写外键字段
'''

from django.contrib.auth.models import AbstractUser

#站点表

class Blog(models.Model):
    site_name=models.CharField(verbose_name='站点名称',max_length=32)
    site_title = models.CharField(verbose_name='站点标题', max_length=32,default='这人很懒，什么都没有留下')
    #简单卖模拟，认识样式内部原理的操作,保存样式文件路径
    site_theme=models.CharField('站点样式',max_length=64)
    # class Meta:
    #     verbose_name_plural='站点表'
    def __str__(self):
        return self.site_name

#用户
class UserInfo(AbstractUser):
    phone = models.BigIntegerField(verbose_name='手机号',null=True,blank=True)
    #头像
    avatar = models.FileField(upload_to='avatar/',default='avatar/default.jpg')
    '''
    给avatar字段传外键对象，该文件会自动存储到media/avatar，用户不上传就默认使用图片。
    '''
    create_time = models.DateField(auto_now_add=True)
    #用户与站点是一对一关系,先设置可为空，因为站点没有那么快生成，只有方便创建用户
    blog = models.OneToOneField(to=Blog,null=True,on_delete=models.CASCADE)
    #用户与上传的文件资源的关系是一对多。外键在多上
    #用户与用户的关注问题是多对多关系
    friends = models.ManyToManyField(to='self', through='User2User', through_fields=('fans_user', 'star_user'), symmetrical=False)
    is_active = models.BooleanField(default=1)
    #禁言的字段,1代表被禁言了
    limit = models.BooleanField(default=0)
    #用户班级
    stu_class = models.CharField(max_length=30,default='200732')
    # class Meta:
    #     verbose_name_plural = '用户表'
    def __str__(self):
        return self.username

#用一张表来记录用户的关注问题
class User2User(models.Model):
    fans_user = models.ForeignKey(to=UserInfo, related_name="fans_user", on_delete=models.CASCADE)
    star_user = models.ForeignKey(to=UserInfo, related_name='star_user', on_delete=models.CASCADE)
    crete_time = models.DateField(auto_now_add=True,null=True)

 #文章分类表
class Category(models.Model):
    name = models.CharField(verbose_name='文章分类',max_length=32)
    #站点与分类是一对多。
    blog = models.ForeignKey(to=Blog,on_delete=models.CASCADE,null=True)

    # class Meta:
    #     verbose_name_plural = '文章分类表'
    def __str__(self):
        return self.name

#标签
class Tag(models.Model):
    name = models.CharField(verbose_name='文章标签',max_length=32)
    #站点与标签是一对多
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE, null=True)

    # class Meta:
    #     verbose_name_plural = '文章标签表'
    def __str__(self):
        return self.name




class Article(models.Model):
    title = models.CharField(verbose_name='文章标题',max_length=64)
    desc = models.CharField(verbose_name='文章简介',max_length=256)
    content =models.TextField(verbose_name='文章内容')
    create_time = models.DateField(verbose_name='创建时间',auto_now_add=True) #创建时记录时间

    #数据库字段优化设计
    up_num = models.BigIntegerField(verbose_name='点赞数',default=0)
    down_num = models.BigIntegerField(verbose_name='点踩',default=0)
    comment_num=models.BigIntegerField(verbose_name='评论数',default=0)

    #外键字段
    #站点与文章是一对多
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE, null=True)
    #文章与标签是多对多，三种创建方式，半自动
    tags = models.ManyToManyField(to=Tag,through='Article2Tag',through_fields=('article','tag')) #表顺序
    #分类与文章1对多
    category = models.ForeignKey(to=Category,on_delete=models.CASCADE,null=True)
    #代表文章的状态,删除与否
    is_active = models.BooleanField(default=1)

    # class Meta:
    #     verbose_name_plural='文章表' #修改admin后台管理默认的表名
    def __str__(self):
        return self.title
class UserFile(models.Model):
    name=models.CharField(verbose_name='文件名',max_length=50,)
    filename = models.CharField(verbose_name='文件带后缀的名字',max_length=50,null=True)
    share = models.BooleanField(default=1,verbose_name='可共享')
    desc = models.CharField(verbose_name='文件描述',max_length=200,null=True)
    #用户上传的共享文件保存到，media文件夹中的user_file文件夹中
    file = models.FileField(upload_to='user_file/')
    #用户上传文件的时间
    create_time = models.DateField(auto_now_add=True,null=True)
    #该文件被下载的次数
    number = models.IntegerField(default=0)
    #标志文件是否删除了
    is_active = models.BooleanField(verbose_name='是否活跃',default=1)
    #用户与上传的文件的关系是一对多的关系，所以外键在多上
    userinfo = models.ForeignKey(to=UserInfo,on_delete=models.CASCADE)

class AdminFile(models.Model):
    name = models.CharField(verbose_name='文件名', max_length=50, null=True)
    filename = models.CharField(verbose_name='文件带后缀的名字', max_length=50, null=True)
    file = models.FileField(upload_to='admin_file/')
    is_active = models.BooleanField(default=1)
    #该文件是否被导入过
    status = models.BooleanField(default=0)
    userinfo = models.ForeignKey(to=UserInfo, on_delete=models.CASCADE)

#文章与标签的第三章表，半自动
class Article2Tag(models.Model):
    article = models.ForeignKey(to=Article,on_delete=models.CASCADE)
    tag = models.ForeignKey(to=Tag,on_delete=models.CASCADE)

    # class Meta:
    #     verbose_name_plural = '文章点赞表'



#点赞点踩表
class UpAndDown(models.Model):
    user = models.ForeignKey(to=UserInfo,on_delete=models.CASCADE)
    article = models.ForeignKey(to=Article,on_delete=models.CASCADE)
    is_up = models.BooleanField() #传布尔值，存0和1.

    # class Meta:
    #     verbose_name_plural = '点赞点踩表'
#
#评论表
class Comment(models.Model):
    user = models.ForeignKey(to=UserInfo, on_delete=models.CASCADE)
    article = models.ForeignKey(to=Article, on_delete=models.CASCADE)
    #评论内容
    content =models.CharField(verbose_name='评论内容',max_length=256)
    comment_time = models.DateTimeField(verbose_name='评论时间',auto_now_add=True)
    #自关联，
    parent = models.ForeignKey(to='self',on_delete=models.CASCADE,null=True) #有些论是根评论
    # is_delete = models.BooleanField(default=False)
    # class Meta:
    #     verbose_name_plural = '评论表'

#用户与文件收藏是多对多的关系,用第三张表来表示
class User2Article(models.Model):
    user = models.ForeignKey(to=UserInfo,on_delete=models.CASCADE)
    article = models.ForeignKey(to=Article,on_delete=models.CASCADE)
    #收藏状态
    static= models.BooleanField(null=True)
    create_time = models.DateField(auto_now_add=True)

#用户与文章收藏是多对多的关系,用第三张表来表示
class User2File(models.Model):
    user = models.ForeignKey(to=UserInfo, on_delete=models.CASCADE)
    file = models.ForeignKey(to=UserFile, on_delete=models.CASCADE)
    # 收藏状态
    static = models.BooleanField(null=True)
    create_time = models.DateField(auto_now_add=True)



#私信表
class User2UserWechat(models.Model):
    send = models.SmallIntegerField(verbose_name='发送者')
    recv = models.SmallIntegerField(verbose_name='接收者')
    content = models.TextField(verbose_name='聊天内容')
    create_time = models.DateTimeField(auto_now_add=True,null=True)
    status = models.IntegerField(choices=((1,'未读'),(2,'已读'),(3,'发送方删除'),(4,'接收方删除')),default=1)

#资源分类表
class Categorys(models.Model):
    categoryid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    descn = models.CharField(max_length=200)
    create_time = models.DateField(auto_now_add=True,null=True)
    userinfo = models.ForeignKey(to=UserInfo,on_delete=models.CASCADE,null=True)

#资源信息表
class Resource(models.Model):
    resourceid = models.AutoField(primary_key=True)
    categoryid = models.ForeignKey(to=Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    descn = models.CharField(max_length=200)
    image = models.FileField(upload_to='resoure_img',null=True)
    code = models.FileField(upload_to='code_file',null=True)
    filename= models.CharField(max_length=32,null=True)
    is_delete=models.BooleanField(default=False)
    level = models.IntegerField(choices=((1,'高级'),(2,'中级'),(3,'初级')),default=3)
    uploader = models.ForeignKey(to=UserInfo,on_delete=models.CASCADE,null=True)
    down_numbers = models.IntegerField(default=0)
    create_time = models.DateField(auto_now_add=True,null=True)

#用户与资源的收藏是多对多的关系
class User2Source(models.Model):
    user_id = models.ForeignKey(to=UserInfo,on_delete=models.CASCADE)
    source_id =models.ForeignKey(to=Resource,on_delete=models.CASCADE)
    create_time = models.DateField(auto_now_add=True)

app01/templates/app01/web_sourse/detail_souce.html
{% extends 'app01/site.html' %}
{% block files %}

{% endblock %}
{% block content %}

    <div class="col-md-10">
        <!--文章显示内容详细内容开始-->
        <h1>控件名字：{{ source.name }} </h1>
        <br>
        <div><h4>
            控件描述：
        </h4> {{ source.descn }}</div>


        <br>
        <div>
            <div class="panel panel-default">
                <div class="panel-heading"><h4>效果图</h4></div>
{#                <div class="panel-heading">#}
{#                    <h3 class="panel-title">Panel title</h3>#}
{#                </div>#}
                <div class="panel-body">
                    <img src="/media/{{ source.image }}" alt="图片加载失败" width="900">
                </div>
            </div>

        </div>
        <br>
        <div class="panel panel-default">
            <div class="panel-heading"><h4>原代码</h4></div>
            <div class="panel-body">
                {% for line in files %}
                    <p>{{ line }}</p>
                {% endfor %}
            </div>
        </div>
     <div class="pull-right" ><!--收藏-->&nbsp;&nbsp;&nbsp;&nbsp;
        <h3>
            <a href="/app01/show_web_source?pk={{ sou_pk }}&username={{ source.uploader.username }}" id="down_source_id">
                下载源代码</a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <label for="img_id" id="div_file_id">  <img src="{{ img }}" alt="" id="img_id"></label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

          <span class="glyphicon glyphicon-download-alt" style="color: #337ab7">下载量(<span id="span_id_down">{{ source.down_numbers }}</span>)</span>
        </h3>

     </div>
    </div>
    <div>
    </div>



    <!--文章显示内容详细内容开始-->
    </div>



    <div class="row" style="text-align: right"><h2>精英计划，联系 <span
            class="glyphicon glyphicon-phone-alt"></span>1232222，<span class="glyphicon glyphicon-envelope"></span>123@12233.com
    </h2></div>

    </div>
{% endblock %}



{% block js %}
    <script>
    //给下载源代码加一个点击事件，在前端渲染下载数
    $('#down_source_id').click(function () {
        let old_num = $('#span_id_down').text()
        let new_num = parseInt(old_num) + 1
        $('#span_id_down').text(new_num)

    })

        //关注的ajax请求
        $('#focu_btn_id').click(function () {
            $.ajax({
                url: '/app01/focu/user/',
                type: 'get',
                data: {'my_name': '{{ request.user.username }}', 'focu_name': '{{ username }}'},
                success: function (array) {
                    alert(array.msg)
                }
            })

        })


    //收藏的ajax
      //给收藏设置一个点击事件。
    $('#div_file_id').on('click',function () {

        if('{{ col_file }}'==='no'){ //用户未收藏，现在想收藏该文章
            alert('收藏成功')
            $('#div_file_id>img').attr('src','/static/img/active.png/')

            $.ajax({
                url:'',
                type:'post',
                data:{
                    'operate':true,//代表加入收藏
                    'file_id':'{{  sou_pk }}',
                },
                success:function (attr) {
                   window.location.reload()//需要刷新后，才能再次使用
                    //因为我们的判断条件是由函数 article_detail发送的col_img
                    //而我们这里发送的是ajax请求，局部刷新，异步请求，原来的col_img不会变，保持一开始访问页面的值。
                    //所以需要刷新来更新col_img的值

                }
            })
        }
        else if('{{ col_file }}'==='yes')//代表用户已经收藏，现在要取消收藏
        {
            alert('取消收藏')
            {#$('#div_img_id').firstChild.attr('src','/static/img/noactive.png/')#}
            $('#div_file_id>img').attr('src','/static/img/noactive.png/')
            $.ajax({
                url:'',
                type:'post',
                data:{
                    'operate':false, //代表取消收藏
                    'file_id':'{{  sou_pk }}',
                },
                success:function (attr) {

                     window.location.reload()//需要刷新后，才能再次使用

                }
            })
        }

    })

    </script>
{% endblock %}

app01/templates/app01/web_sourse/home_article_left.html
<div class="list-group">
  <a href="#" class="list-group-item " style="background-color: rgba(219,112,147,0.43)">
    推荐的帖子
  </a>
 {% for source in good_article %}
    <a href="/app01/site/{{ source.blog.userinfo.username }}/article/{{ source.pk }}/?url={{ request.get_full_path }}" class="list-group-item">{{ source.title }}</a>

 {% endfor %}

</div>

<div class="list-group">
  <a href="#" class="list-group-item " style="background-color: rgba(219,112,147,0.43)">
    推荐的web资源
  </a>
 {% for source in good_source %}
    <a href="/app01/site/{{source.uploader.username}}/source_detail/{{ source.pk }}?pk={{ source.pk }}&url={{ request.get_full_path }}" class="list-group-item">{{ source.name }}({{ source.down_numbers }})</a>
 {% endfor %}

</div>

app01/templates/app01/web_sourse/home_article_right.html
<div class="list-group">
  <a href="#" class="list-group-item" style="background-color: rgba(219,112,147,0.43)">
    最新发布的帖子
  </a>
 {% for source in new_article %}
    <a href="/app01/site/{{ source.blog.userinfo.username }}/article/{{ source.pk }}/?url={{ request.get_full_path }}" class="list-group-item">{{ source.title }}</a>

 {% endfor %}

</div>

<div class="list-group">
  <a href="#" class="list-group-item " style="background-color: rgba(219,112,147,0.43)">
    最新上传的web资源
  </a>
 {% for source in new_source %}
    <a href="/app01/site/{{source.uploader.username}}/source_detail/{{ source.pk }}?pk={{ source.pk }}&url={{ request.get_full_path }}" class="list-group-item">{{ source.name }}({{ source.down_numbers }})</a>
 {% endfor %}

</div>

app01/templates/app01/web_sourse/home_bote_left.html
<div class="list-group" >
  <a href="#" class="list-group-item " style="background-color: rgba(134,226,123,0.52)">
    推荐的笔记
  </a>
 {% for source in good_file %}
    <a href="/app01/preview_file/?file_id={{ source.pk }}&url={{ request.get_full_path }}" class="list-group-item">
        {{ source.name }}({{ source.number }})</a>
 {% endfor %}

</div>

<div class="list-group">
  <a href="#" class="list-group-item " style="background-color: rgba(134,226,123,0.52)">
    推荐的资源
  </a>
 {% for source in good_source %}
    <a href="/app01/site/{{ source.uploader.username }}/source_detail/{{ source.pk }}/?pk={{ source.pk }}&url={{ request.get_full_path }}" class="list-group-item">
        {{ source.name }}</a>

 {% endfor %}

</div>

app01/templates/app01/web_sourse/index.html
{% extends 'app01/home.html' %}
{% block left %}
    {% load my_tag %} <!--加载inclusion_tag函数-->
    {% home_left request %}

{% endblock %}
{% block right %}
    {% load my_tag %} <!--加载inclusion_tag函数-->
    {% home_right request %}

{% endblock %}

{% block center_content %}
    <!--页面的内容开始-->
    <div class="text-center">
        <h3>web资源库</h3>
    </div>

    <div>
        {% for page in c_page %}
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object img-circle" height="64" src="/media/{{ page.uploader.avatar }}/"
                             alt="...">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading" style="color: #12493e">

                        <a href="/app01/site/{{ page.uploader.username }}/source_detail/{{ page.pk }}?pk={{ page.pk }}&url={{ request.get_full_path_info }}"
                           target="_blank">
                            资源名：{{ page.name }} </a>
                    </h4>
                    <p>资源描述：{{ page.descn }}</p>

                    <div class="pull-left" style="color: #004d88">
                        <a href="/app01/site/{{ page.uploader.username }}?url={{ request.get_full_path_info }}">上传者:{{ page.uploader.username }}</a>&nbsp;&nbsp;
                        &nbsp;&nbsp;
                        <span>资源等级：{{ page.get_level_display }}</span>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <span class="glyphicon glyphicon-download-alt">下载数({{ page.down_numbers }})</span>

                    </div>
                </div>
            </div>
            <hr>
        {% endfor %}
    </div>

    <!--页面的内容结束-->

    {# 分页显示 #}
    <div class="pager">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_html }}
            </ul>
        </nav>
    </div>

{% endblock %}

{% block js %}


    <script>
        $('#id_editer').on('click', function () {
            let old_pwd = $('#id_old_pwd').val()
            let new_pwd = $('#id_new_pwd').val()
            let confirm_pwd = $('#id_confirm_pwd').val()
            $.ajax({
                url: '/app01/set_password/',
                type: 'post',
                data: {
                    'old_pwd': old_pwd,
                    'new_pwd': new_pwd,
                    'confirm_pwd': confirm_pwd,
                    //'csrfmiddlewaretoken':{{ csrf_token }}
                },
                success: function (array) {
                    if (array.code === 1000) {
                        {#parent.location.href='/app01/login/'#}
                        //刷新当前url
                        alert('修改密码成功，重新登录')
                        window.location.reload()
                    } else {
                        $('#error').text(array.msg)
                    }

                }
            })

        });


        //前端渲染下载数。
        $('.down_file_class').click(function () {
            let old_number = $(this).prev().text()
            let new_number = parseInt(old_number) + 1
            $(this).prev().text(new_number)
            //用户下载自己的文件，下载数不会增加1
        })
    </script>

{% endblock %}

app01/templates/app01/web_sourse/show_web_source.html
{% extends 'app01/base_backend.html' %}
{% block person_manage %}
    <a class="navbar-brand" href="#">我的web资源</a>
{% endblock %}
{% block all_li %}
    <li role="presentation">
        <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">我的web资源</a>
    </li>
    <li role="presentation" class="active">
        <a href="{% url 'app01_backend' %}" style="color: #337ab7">返回个人管理</a></li>
{% endblock %}

{% block all_content %}
    {% block caogao %}
        <div class="panel panel-default">
            <div class="panel-heading">我的web资源</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 ">
                        <table class="table table-hover table-striped">
                            <thead>
                            <tr>
                                <th>资源名字</th>
                                <th>资源描述</th>
                                <th>等级</th>
                                <th>原代码</th>
                                <th>操作</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for source in c_page %}
                                <tr>
                                    <td>{{ source.name }}</td>
                                    <td>
                                        <a href="/app01/site/{{ source.uploader.username }}/source_detail/{{ source.pk }}/?pk={{ source.pk }}&url={{ request.get_full_path }}">{{ source.descn }}</a>
                                    </td>
                                    <td>{{ source.get_level_display }}</td>
                                    <td><a href="/app01/show_web_source?pk={{ source.pk }}">下载</a></td>
                                    <td><a href="/app01/editer/source?source_id={{ source.pk }}&url={{ request.get_full_path }}">修改</a></td>
                                    <td><a href="#" class="del_suorce_class" del_id="{{ source.pk }}">删除</a></td>
                                </tr>

                            {% endfor %}


                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>



        {# 分页显示 #}
        <div class="pager">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ page_html }}
                </ul>
            </nav>
        </div>
    {% endblock %}

{% endblock %}
{% block js %}
    <script>
        if ('{{ request.user.username }}'.slice(0, 3) === '512') {
            $('#p_for_a').html('<a href="/app01/manage_student/" class="list-group-item">学生管理</a>')
            $('#role_for').html('角色：<br><a href="#">老师</a>')
        }


        if ('{{ request.user.username }}'.slice(0, 3) === '312') {

            $('#set_person_id').html('<p>班级：<input type="text" id="stu_class" class="form-control" value="{{ request.user.stu_class }}"></p>')
            $('#role_for').html('角色：<br><a href="#">学生</a>')
        }
        //删除资源的ajax请求
        $('.del_suorce_class').click(function () {
            let op = confirm('是否确认删除？')
            let source_id = $(this).attr('del_id')
            if (op === true) {
                $.ajax({
                    url: '',
                    type: 'post',
                    data: {'op': op, 'del_id': source_id},
                    success: function (attr) {
                        if (attr.code === 100) {
                            alert(attr.msg)
                            window.location.reload()
                        } else {
                            alert(attrmsg)
                        }

                    }
                })
            }

        })

        //文件上传的ajax请求
        $("#up_btn_id").click(function () {
            let formObj = new FormData()
            formObj.append('file', $('#up_file_id')[0].files[0])
            formObj.append('filename', $('#file_name_id').val())
            formObj.append('desc', $('#file_desc_id').val())
            let radio_chioce = $('input[name="share"]:checked').val();
            formObj.append('share', radio_chioce)

            $.ajax({
                url: "/app01/upload_file/",
                type: 'post',
                data: formObj,
                contentType: false,
                processData: false,
                success: function (array) {
                    if (array.code === 1000) {
                        alert(array.msg0)
                        parent.location.href = array.url
                    } else if (array.code === 2000) {
                        //用户输入不正确的提示
                        $('#p1').next().text(array.msg1)
                        $('#p2').next().text(array.msg2)
                        $('#p3').next().text(array.msg3)
                    } else {
                        alert(array.msg0)
                    }

                }
            })


        });

    </script>
{% endblock %}